name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v1

    - name: podman
      run: | 
        podman pull alpine:latest
        podman images -a
        podman run -t -i alpine:latest echo HELLO

